{
 "bad": false,
 "new_version": "2024.1",
 "new_version_attempts": {
  "2020.1": 346,
  "2021.1": 110,
  "2021.2": 5,
  "2021.2.1": 1,
  "2021.2.2": 78,
  "2022.1": 7,
  "2022.1.1": 72,
  "2022.1.2": 19,
  "2022.1.3": 2,
  "2023.1": 46,
  "2024.1": 55
 },
 "new_version_errors": {
  "2020.1": "We found a problem parsing the recipe for version '2020.1': \n\nDuplicateKeyError('while constructing a mapping', <ruamel.yaml.error.StringMark object at 0x7fe3f5e134a0>, 'found duplicate key \"commands\" with value \"[\\'cd test && python -m pytest\\']\" (original value: \"[\\'pudb --help\\']\")', <ruamel.yaml.error.StringMark object at 0x7fe359602740>, '\\n                    To suppress this check see:\\n                        http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys\\n                    ', '                    Duplicate keys will become an error in future releases, and are errors\\n                    by default when using the new API.\\n                    ')\n\ntraceback:\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/migrators/version.py\", line 472, in migrate\n    cmeta = CondaMetaYAML(fp.read())\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/recipe_parser/_parser.py\", line 455, in __init__\n    self.meta = self._parser.load(\"\".join(lines))\n  File \"/usr/share/miniconda/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/main.py\", line 343, in load\n    return constructor.get_single_data()\n  File \"/usr/share/miniconda/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 113, in get_single_data\n    return self.construct_document(node)\n  File \"/usr/share/miniconda/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 123, in construct_document\n    for _dummy in generator:\n  File \"/usr/share/miniconda/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 1563, in construct_yaml_map\n    self.construct_mapping(node, data, deep=True)\n  File \"/usr/share/miniconda/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 1469, in construct_mapping\n    value = self.construct_object(value_node, deep=deep)\n  File \"/usr/share/miniconda/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 146, in construct_object\n    data = self.construct_non_recursive_object(node)\n  File \"/usr/share/miniconda/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 188, in construct_non_recursive_object\n    for _dummy in generator:\n  File \"/usr/share/miniconda/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 1563, in construct_yaml_map\n    self.construct_mapping(node, data, deep=True)\n  File \"/usr/share/miniconda/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 1470, in construct_mapping\n    if self.check_mapping_key(node, key_node, maptyp, key, value):\n  File \"/usr/share/miniconda/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 295, in check_mapping_key\n    raise DuplicateKeyError(*args)\n",
  "2021.1": "We found a problem parsing the recipe for version '2021.1': \n\nDuplicateKeyError('while constructing a mapping',   in \"<unicode string>\", line 30, column 3:\n      requires:\n      ^ (line: 30), 'found duplicate key \"commands\" with value \"[\\'cd test && python -m pytest\\']\" (original value: \"[\\'pudb --help\\']\")',   in \"<unicode string>\", line 39, column 3:\n      commands:\n      ^ (line: 39), '\\n                    To suppress this check see:\\n                        http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys\\n                    ', '                    Duplicate keys will become an error in future releases, and are errors\\n                    by default when using the new API.\\n                    ')\n\ntraceback:\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/migrators/version.py\", line 506, in migrate\n    cmeta = CondaMetaYAML(fp.read())\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/recipe_parser/_parser.py\", line 455, in __init__\n    self.meta = self._parser.load(\"\".join(lines))\n  File \"/usr/share/miniconda/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/main.py\", line 434, in load\n    return constructor.get_single_data()\n  File \"/usr/share/miniconda/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 122, in get_single_data\n    return self.construct_document(node)\n  File \"/usr/share/miniconda/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 132, in construct_document\n    for _dummy in generator:\n  File \"/usr/share/miniconda/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 1617, in construct_yaml_map\n    self.construct_mapping(node, data, deep=True)\n  File \"/usr/share/miniconda/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 1500, in construct_mapping\n    value = self.construct_object(value_node, deep=deep)\n  File \"/usr/share/miniconda/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 155, in construct_object\n    data = self.construct_non_recursive_object(node)\n  File \"/usr/share/miniconda/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 197, in construct_non_recursive_object\n    for _dummy in generator:\n  File \"/usr/share/miniconda/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 1617, in construct_yaml_map\n    self.construct_mapping(node, data, deep=True)\n  File \"/usr/share/miniconda/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 1501, in construct_mapping\n    if self.check_mapping_key(node, key_node, maptyp, key, value):\n  File \"/usr/share/miniconda/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 295, in check_mapping_key\n    raise DuplicateKeyError(*args)\n",
  "2021.2": "We found a problem parsing the recipe for version '2021.2': \n\nDuplicateKeyError('while constructing a mapping',   in \"<unicode string>\", line 29, column 3:\n      requires:\n      ^ (line: 29), 'found duplicate key \"commands\" with value \"[\\'cd test && python -m pytest\\']\" (original value: \"[\\'pudb --help\\']\")',   in \"<unicode string>\", line 38, column 3:\n      commands:\n      ^ (line: 38), '\\n                    To suppress this check see:\\n                        http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys\\n                    ', '                    Duplicate keys will become an error in future releases, and are errors\\n                    by default when using the new API.\\n                    ')\n\ntraceback:\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/migrators/version.py\", line 508, in migrate\n    cmeta = CondaMetaYAML(fp.read())\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/recipe_parser/_parser.py\", line 465, in __init__\n    self.meta = self._parser.load(\"\".join(lines))\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/main.py\", line 434, in load\n    return constructor.get_single_data()\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 122, in get_single_data\n    return self.construct_document(node)\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 132, in construct_document\n    for _dummy in generator:\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 1617, in construct_yaml_map\n    self.construct_mapping(node, data, deep=True)\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 1500, in construct_mapping\n    value = self.construct_object(value_node, deep=deep)\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 155, in construct_object\n    data = self.construct_non_recursive_object(node)\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 197, in construct_non_recursive_object\n    for _dummy in generator:\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 1617, in construct_yaml_map\n    self.construct_mapping(node, data, deep=True)\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 1501, in construct_mapping\n    if self.check_mapping_key(node, key_node, maptyp, key, value):\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 295, in check_mapping_key\n    raise DuplicateKeyError(*args)\n",
  "2021.2.1": "We found a problem parsing the recipe for version '2021.2.1': \n\nDuplicateKeyError('while constructing a mapping',   in \"<unicode string>\", line 29, column 3:\n      requires:\n      ^ (line: 29), 'found duplicate key \"commands\" with value \"[\\'cd test && python -m pytest\\']\" (original value: \"[\\'pudb --help\\']\")',   in \"<unicode string>\", line 38, column 3:\n      commands:\n      ^ (line: 38), '\\n                    To suppress this check see:\\n                        http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys\\n                    ', '                    Duplicate keys will become an error in future releases, and are errors\\n                    by default when using the new API.\\n                    ')\n\ntraceback:\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/migrators/version.py\", line 508, in migrate\n    cmeta = CondaMetaYAML(fp.read())\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/recipe_parser/_parser.py\", line 465, in __init__\n    self.meta = self._parser.load(\"\".join(lines))\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/main.py\", line 434, in load\n    return constructor.get_single_data()\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 122, in get_single_data\n    return self.construct_document(node)\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 132, in construct_document\n    for _dummy in generator:\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 1617, in construct_yaml_map\n    self.construct_mapping(node, data, deep=True)\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 1500, in construct_mapping\n    value = self.construct_object(value_node, deep=deep)\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 155, in construct_object\n    data = self.construct_non_recursive_object(node)\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 197, in construct_non_recursive_object\n    for _dummy in generator:\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 1617, in construct_yaml_map\n    self.construct_mapping(node, data, deep=True)\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 1501, in construct_mapping\n    if self.check_mapping_key(node, key_node, maptyp, key, value):\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 295, in check_mapping_key\n    raise DuplicateKeyError(*args)\n",
  "2021.2.2": "We found a problem parsing the recipe for version '2021.2.2': \n\nDuplicateKeyError('while constructing a mapping',   in \"<unicode string>\", line 29, column 3:\n      requires:\n      ^ (line: 29), 'found duplicate key \"commands\" with value \"[\\'cd test && python -m pytest\\']\" (original value: \"[\\'pudb --help\\']\")',   in \"<unicode string>\", line 38, column 3:\n      commands:\n      ^ (line: 38), '\\n                    To suppress this check see:\\n                        http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys\\n                    ', '                    Duplicate keys will become an error in future releases, and are errors\\n                    by default when using the new API.\\n                    ')\n\ntraceback:\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/migrators/version.py\", line 508, in migrate\n    cmeta = CondaMetaYAML(fp.read())\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/recipe_parser/_parser.py\", line 465, in __init__\n    self.meta = self._parser.load(\"\".join(lines))\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/main.py\", line 434, in load\n    return constructor.get_single_data()\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 121, in get_single_data\n    return self.construct_document(node)\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 131, in construct_document\n    for _dummy in generator:\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 1569, in construct_yaml_map\n    self.construct_mapping(node, data, deep=True)\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 1452, in construct_mapping\n    value = self.construct_object(value_node, deep=deep)\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 154, in construct_object\n    data = self.construct_non_recursive_object(node)\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 196, in construct_non_recursive_object\n    for _dummy in generator:\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 1569, in construct_yaml_map\n    self.construct_mapping(node, data, deep=True)\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 1453, in construct_mapping\n    if self.check_mapping_key(node, key_node, maptyp, key, value):\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 294, in check_mapping_key\n    raise DuplicateKeyError(*args)\n",
  "2022.1": "We found a problem parsing the recipe for version '2022.1': \n\nDuplicateKeyError('while constructing a mapping',   in \"<unicode string>\", line 29, column 3:\n      requires:\n      ^ (line: 29), 'found duplicate key \"commands\" with value \"[\\'cd test && python -m pytest\\']\" (original value: \"[\\'pudb --help\\']\")',   in \"<unicode string>\", line 38, column 3:\n      commands:\n      ^ (line: 38), '\\n                    To suppress this check see:\\n                        http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys\\n                    ', '                    Duplicate keys will become an error in future releases, and are errors\\n                    by default when using the new API.\\n                    ')\n\ntraceback:\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/migrators/version.py\", line 508, in migrate\n    cmeta = CondaMetaYAML(fp.read())\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/recipe_parser/_parser.py\", line 465, in __init__\n    self.meta = self._parser.load(\"\".join(lines))\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/main.py\", line 434, in load\n    return constructor.get_single_data()\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 121, in get_single_data\n    return self.construct_document(node)\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 131, in construct_document\n    for _dummy in generator:\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 1569, in construct_yaml_map\n    self.construct_mapping(node, data, deep=True)\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 1452, in construct_mapping\n    value = self.construct_object(value_node, deep=deep)\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 154, in construct_object\n    data = self.construct_non_recursive_object(node)\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 196, in construct_non_recursive_object\n    for _dummy in generator:\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 1569, in construct_yaml_map\n    self.construct_mapping(node, data, deep=True)\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 1453, in construct_mapping\n    if self.check_mapping_key(node, key_node, maptyp, key, value):\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 294, in check_mapping_key\n    raise DuplicateKeyError(*args)\n",
  "2022.1.1": "We found a problem parsing the recipe for version '2022.1.1': \n\nDuplicateKeyError('while constructing a mapping',   in \"<unicode string>\", line 30, column 3:\n      requires:\n      ^ (line: 30), 'found duplicate key \"commands\" with value \"[\\'cd test && python -m pytest\\']\" (original value: \"[\\'pudb --help\\']\")',   in \"<unicode string>\", line 39, column 3:\n      commands:\n      ^ (line: 39), '\\n                    To suppress this check see:\\n                        http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys\\n                    ', '                    Duplicate keys will become an error in future releases, and are errors\\n                    by default when using the new API.\\n                    ')\n\ntraceback:\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/migrators/version.py\", line 509, in migrate\n    cmeta = CondaMetaYAML(fp.read())\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/recipe_parser/_parser.py\", line 494, in __init__\n    self.meta = self._parser.load(\"\".join(lines))\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/main.py\", line 434, in load\n    return constructor.get_single_data()\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 121, in get_single_data\n    return self.construct_document(node)\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 131, in construct_document\n    for _dummy in generator:\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 1569, in construct_yaml_map\n    self.construct_mapping(node, data, deep=True)\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 1452, in construct_mapping\n    value = self.construct_object(value_node, deep=deep)\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 154, in construct_object\n    data = self.construct_non_recursive_object(node)\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 196, in construct_non_recursive_object\n    for _dummy in generator:\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 1569, in construct_yaml_map\n    self.construct_mapping(node, data, deep=True)\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 1453, in construct_mapping\n    if self.check_mapping_key(node, key_node, maptyp, key, value):\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 294, in check_mapping_key\n    raise DuplicateKeyError(*args)\n",
  "2022.1.2": "We found a problem parsing the recipe for version '2022.1.2': \n\nDuplicateKeyError('while constructing a mapping',   in \"<unicode string>\", line 30, column 3:\n      requires:\n      ^ (line: 30), 'found duplicate key \"commands\" with value \"[\\'cd test && python -m pytest\\']\" (original value: \"[\\'pudb --help\\']\")',   in \"<unicode string>\", line 39, column 3:\n      commands:\n      ^ (line: 39), '\\n                    To suppress this check see:\\n                        http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys\\n                    ', '                    Duplicate keys will become an error in future releases, and are errors\\n                    by default when using the new API.\\n                    ')\n\ntraceback:\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/migrators/version.py\", line 513, in migrate\n    cmeta = CondaMetaYAML(fp.read())\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/recipe_parser/_parser.py\", line 494, in __init__\n    self.meta = self._parser.load(\"\".join(lines))\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/main.py\", line 434, in load\n    return constructor.get_single_data()\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 121, in get_single_data\n    return self.construct_document(node)\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 131, in construct_document\n    for _dummy in generator:\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 1569, in construct_yaml_map\n    self.construct_mapping(node, data, deep=True)\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 1452, in construct_mapping\n    value = self.construct_object(value_node, deep=deep)\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 154, in construct_object\n    data = self.construct_non_recursive_object(node)\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 196, in construct_non_recursive_object\n    for _dummy in generator:\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 1569, in construct_yaml_map\n    self.construct_mapping(node, data, deep=True)\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 1453, in construct_mapping\n    if self.check_mapping_key(node, key_node, maptyp, key, value):\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 294, in check_mapping_key\n    raise DuplicateKeyError(*args)\n",
  "2022.1.3": "We found a problem parsing the recipe for version '2022.1.3': \n\nDuplicateKeyError('while constructing a mapping',   in \"<unicode string>\", line 29, column 3:\n      requires:\n      ^ (line: 29), 'found duplicate key \"commands\" with value \"[\\'cd test && python -m pytest\\']\" (original value: \"[\\'pudb --help\\']\")',   in \"<unicode string>\", line 38, column 3:\n      commands:\n      ^ (line: 38), '\\n                    To suppress this check see:\\n                        http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys\\n                    ', '                    Duplicate keys will become an error in future releases, and are errors\\n                    by default when using the new API.\\n                    ')\n\ntraceback:\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/migrators/version.py\", line 513, in migrate\n    cmeta = CondaMetaYAML(fp.read())\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/recipe_parser/_parser.py\", line 494, in __init__\n    self.meta = self._parser.load(\"\".join(lines))\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/main.py\", line 434, in load\n    return constructor.get_single_data()\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 121, in get_single_data\n    return self.construct_document(node)\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 131, in construct_document\n    for _dummy in generator:\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 1569, in construct_yaml_map\n    self.construct_mapping(node, data, deep=True)\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 1452, in construct_mapping\n    value = self.construct_object(value_node, deep=deep)\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 154, in construct_object\n    data = self.construct_non_recursive_object(node)\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 196, in construct_non_recursive_object\n    for _dummy in generator:\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 1569, in construct_yaml_map\n    self.construct_mapping(node, data, deep=True)\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 1453, in construct_mapping\n    if self.check_mapping_key(node, key_node, maptyp, key, value):\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 294, in check_mapping_key\n    raise DuplicateKeyError(*args)\n",
  "2023.1": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '2023.1' to make sure they exist!\n\nWe also found the following errors:\n\n - We found a problem parsing the recipe for version '2023.1': \n\nDuplicateKeyError('while constructing a mapping',   in \"<unicode string>\", line 29, column 3:\n      requires:\n      ^ (line: 29), 'found duplicate key \"commands\" with value \"[\\'cd test && python -m pytest\\']\" (original value: \"[\\'pudb --help\\']\")',   in \"<unicode string>\", line 38, column 3:\n      commands:\n      ^ (line: 38), '\\n                    To suppress this check see:\\n                        http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys\\n                    ', '                    Duplicate keys will become an error in future releases, and are errors\\n                    by default when using the new API.\\n                    ')\n\ntraceback:\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/update_recipe/version.py\", line 411, in update_version\n    cmeta = CondaMetaYAML(raw_meta_yaml)\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/recipe_parser/_parser.py\", line 514, in __init__\n    self.meta = self._parser.load(\"\".join(lines))\n  File \"/home/runner/miniconda3/envs/cf-scripts/lib/python3.10/site-packages/ruamel/yaml/main.py\", line 451, in load\n    return constructor.get_single_data()\n  File \"/home/runner/miniconda3/envs/cf-scripts/lib/python3.10/site-packages/ruamel/yaml/constructor.py\", line 114, in get_single_data\n    return self.construct_document(node)\n  File \"/home/runner/miniconda3/envs/cf-scripts/lib/python3.10/site-packages/ruamel/yaml/constructor.py\", line 123, in construct_document\n    for _dummy in generator:\n  File \"/home/runner/miniconda3/envs/cf-scripts/lib/python3.10/site-packages/ruamel/yaml/constructor.py\", line 1470, in construct_yaml_map\n    self.construct_mapping(node, data, deep=True)\n  File \"/home/runner/miniconda3/envs/cf-scripts/lib/python3.10/site-packages/ruamel/yaml/constructor.py\", line 1359, in construct_mapping\n    value = self.construct_object(value_node, deep=deep)\n  File \"/home/runner/miniconda3/envs/cf-scripts/lib/python3.10/site-packages/ruamel/yaml/constructor.py\", line 145, in construct_object\n    data = self.construct_non_recursive_object(node)\n  File \"/home/runner/miniconda3/envs/cf-scripts/lib/python3.10/site-packages/ruamel/yaml/constructor.py\", line 186, in construct_non_recursive_object\n    for _dummy in generator:\n  File \"/home/runner/miniconda3/envs/cf-scripts/lib/python3.10/site-packages/ruamel/yaml/constructor.py\", line 1470, in construct_yaml_map\n    self.construct_mapping(node, data, deep=True)\n  File \"/home/runner/miniconda3/envs/cf-scripts/lib/python3.10/site-packages/ruamel/yaml/constructor.py\", line 1360, in construct_mapping\n    if self.check_mapping_key(node, key_node, maptyp, key, value):\n  File \"/home/runner/miniconda3/envs/cf-scripts/lib/python3.10/site-packages/ruamel/yaml/constructor.py\", line 276, in check_mapping_key\n    raise DuplicateKeyError(*args)\n\n",
  "2024.1": "bot error (<a href=\"https://github.com/regro/cf-scripts/actions/runs/9428171377\">bot CI job</a>): main: Traceback (most recent call last):\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py\", line 572, in _run_migrator_on_feedstock_branch\n    migrator_uid, pr_json = run(\n                            ^^^^\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py\", line 216, in run\n    migration_run_data = run_migration(\n                         ^^^^^^^^^^^^^^\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/migration_runner.py\", line 63, in run_migration\n    return run_migration_containerized(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/migration_runner.py\", line 157, in run_migration_containerized\n    data = run_container_task(\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/utils.py\", line 249, in run_container_task\n    raise RuntimeError(\nRuntimeError: Error running migrate-feedstock in container - error VersionMigrationError('The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\\n\\nPlease check the URLs in your recipe with version \\'2024.1\\' to make sure they exist!\\n\\nWe also found the following errors:\\n\\n - We found a problem parsing the recipe for version \\'2024.1\\': \\n\\nDuplicateKeyError(\\'while constructing a mapping\\',   in \"<unicode string>\", line 29, column 3:\\n      requires:\\n      ^ (line: 29), \\'found duplicate key \"commands\" with value \"[\\\\\\'cd test && python -m pytest\\\\\\']\" (original value: \"[\\\\\\'pudb --help\\\\\\']\")\\',   in \"<unicode string>\", line 38, column 3:\\n      commands:\\n      ^ (line: 38), \\'\\\\n                    To suppress this check see:\\\\n                        http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys\\\\n                    \\', \\'                    Duplicate keys will become an error in future releases, and are errors\\\\n                    by default when using the new API.\\\\n                    \\')\\n\\ntraceback:\\n  File \"/opt/autotick-bot/conda_forge_tick/update_recipe/version.py\", line 415, in update_version\\n    cmeta = CondaMetaYAML(raw_meta_yaml)\\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/opt/autotick-bot/conda_forge_tick/recipe_parser/_parser.py\", line 515, in __init__\\n    self.meta = self._parser.load(\"\".join(lines))\\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/ruamel/yaml/main.py\", line 451, in load\\n    return constructor.get_single_data()\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/ruamel/yaml/constructor.py\", line 116, in get_single_data\\n    return self.construct_document(node)\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/ruamel/yaml/constructor.py\", line 125, in construct_document\\n    for _dummy in generator:\\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/ruamel/yaml/constructor.py\", line 1476, in construct_yaml_map\\n    self.construct_mapping(node, data, deep=True)\\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/ruamel/yaml/constructor.py\", line 1365, in construct_mapping\\n    value = self.construct_object(value_node, deep=deep)\\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/ruamel/yaml/constructor.py\", line 147, in construct_object\\n    data = self.construct_non_recursive_object(node)\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/ruamel/yaml/constructor.py\", line 188, in construct_non_recursive_object\\n    for _dummy in generator:\\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/ruamel/yaml/constructor.py\", line 1476, in construct_yaml_map\\n    self.construct_mapping(node, data, deep=True)\\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/ruamel/yaml/constructor.py\", line 1366, in construct_mapping\\n    if self.check_mapping_key(node, key_node, maptyp, key, value):\\n       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/ruamel/yaml/constructor.py\", line 278, in check_mapping_key\\n    raise DuplicateKeyError(*args)\\n\\n') raised:\ncmd: ['docker',\n 'run',\n '-e',\n 'CF_TICK_IN_CONTAINER=true',\n '--security-opt=no-new-privileges',\n '--read-only',\n '--cap-drop=all',\n '--mount',\n 'type=tmpfs,destination=/tmp,tmpfs-mode=1777,tmpfs-size=6000000000',\n '-m',\n '6000m',\n '--cpus',\n '1',\n '--ulimit',\n 'nofile=1024:1024',\n '--ulimit',\n 'nproc=2048:2048',\n '--rm',\n '-i',\n '--mount',\n 'type=bind,source=/tmp/tmp4kf3o6hp,destination=/cf_tick_dir',\n 'ghcr.io/regro/conda-forge-tick:master',\n '/opt/conda/envs/cf-scripts/bin/python',\n '-u',\n '/opt/autotick-bot/docker/run_bot_task.py',\n 'migrate-feedstock',\n '--feedstock-name',\n 'pudb',\n '--default-branch',\n 'main',\n '--existing-feedstock-node-attrs',\n '-',\n '--kwargs',\n '{\\n \"hash_type\": \"sha256\"\\n}',\n '--log-level',\n 'info']\nstdout: {'data': None,\n 'default_branch': 'main',\n 'error': \"VersionMigrationError('The recipe did not change in the version \"\n          'migration, a URL did not hash, or there is jinja2 syntax the bot '\n          'cannot handle!\\\\n\\\\nPlease check the URLs in your recipe with '\n          \"version \\\\'2024.1\\\\' to make sure they exist!\\\\n\\\\nWe also found \"\n          'the following errors:\\\\n\\\\n - We found a problem parsing the recipe '\n          \"for version \\\\'2024.1\\\\': \\\\n\\\\nDuplicateKeyError(\\\\'while \"\n          'constructing a mapping\\\\\\',   in \"<unicode string>\", line 29, '\n          \"column 3:\\\\n      requires:\\\\n      ^ (line: 29), \\\\'found \"\n          'duplicate key \"commands\" with value \"[\\\\\\\\\\\\\\'cd test && python -m '\n          'pytest\\\\\\\\\\\\\\']\" (original value: \"[\\\\\\\\\\\\\\'pudb '\n          '--help\\\\\\\\\\\\\\']\")\\\\\\',   in \"<unicode string>\", line 38, column '\n          '3:\\\\n      commands:\\\\n      ^ (line: 38), '\n          \"\\\\'\\\\\\\\n                    To suppress this check \"\n          'see:\\\\\\\\n                        '\n          'http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys\\\\\\\\n                    '\n          \"\\\\', \\\\'                    Duplicate keys will become an error in \"\n          'future releases, and are errors\\\\\\\\n                    by default '\n          'when using the new API.\\\\\\\\n                    '\n          \"\\\\')\\\\n\\\\ntraceback:\\\\n  File \"\n          '\"/opt/autotick-bot/conda_forge_tick/update_recipe/version.py\", line '\n          '415, in update_version\\\\n    cmeta = '\n          'CondaMetaYAML(raw_meta_yaml)\\\\n            '\n          '^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\\\n  File '\n          '\"/opt/autotick-bot/conda_forge_tick/recipe_parser/_parser.py\", line '\n          '515, in __init__\\\\n    self.meta = '\n          'self._parser.load(\"\".join(lines))\\\\n                '\n          '^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\\\n  File '\n          '\"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/ruamel/yaml/main.py\", '\n          'line 451, in load\\\\n    return '\n          'constructor.get_single_data()\\\\n           '\n          '^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\\\n  File '\n          '\"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/ruamel/yaml/constructor.py\", '\n          'line 116, in get_single_data\\\\n    return '\n          'self.construct_document(node)\\\\n           '\n          '^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\\\n  File '\n          '\"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/ruamel/yaml/constructor.py\", '\n          'line 125, in construct_document\\\\n    for _dummy in generator:\\\\n  '\n          'File '\n          '\"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/ruamel/yaml/constructor.py\", '\n          'line 1476, in construct_yaml_map\\\\n    self.construct_mapping(node, '\n          'data, deep=True)\\\\n  File '\n          '\"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/ruamel/yaml/constructor.py\", '\n          'line 1365, in construct_mapping\\\\n    value = '\n          'self.construct_object(value_node, deep=deep)\\\\n            '\n          '^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\\\n  File '\n          '\"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/ruamel/yaml/constructor.py\", '\n          'line 147, in construct_object\\\\n    data = '\n          'self.construct_non_recursive_object(node)\\\\n           '\n          '^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\\\n  File '\n          '\"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/ruamel/yaml/constructor.py\", '\n          'line 188, in construct_non_recursive_object\\\\n    for _dummy in '\n          'generator:\\\\n  File '\n          '\"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/ruamel/yaml/constructor.py\", '\n          'line 1476, in construct_yaml_map\\\\n    self.construct_mapping(node, '\n          'data, deep=True)\\\\n  File '\n          '\"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/ruamel/yaml/constructor.py\", '\n          'line 1366, in construct_mapping\\\\n    if '\n          'self.check_mapping_key(node, key_node, maptyp, key, '\n          'value):\\\\n       '\n          '^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\\\n  File '\n          '\"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/ruamel/yaml/constructor.py\", '\n          'line 278, in check_mapping_key\\\\n    raise '\n          \"DuplicateKeyError(*args)\\\\n\\\\n')\",\n 'feedstock_name': 'pudb',\n 'input_kwargs': '{\\n \"hash_type\": \"sha256\"\\n}',\n 'traceback': 'Traceback (most recent call last):\\n'\n              '  File \"/opt/autotick-bot/docker/run_bot_task.py\", line 120, in '\n              '_run_bot_task\\n'\n              '    data = func(attrs=attrs, **kwargs)\\n'\n              '           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n'\n              '  File \"/opt/autotick-bot/docker/run_bot_task.py\", line 308, in '\n              '_migrate_feedstock\\n'\n              '    data = run_migration_local(\\n'\n              '           ^^^^^^^^^^^^^^^^^^^^\\n'\n              '  File '\n              '\"/opt/autotick-bot/conda_forge_tick/migration_runner.py\", line '\n              '241, in run_migration_local\\n'\n              '    data[\"migrate_return_value\"] = migrator.migrate(\\n'\n              '                                   ^^^^^^^^^^^^^^^^^\\n'\n              '  File '\n              '\"/opt/autotick-bot/conda_forge_tick/migrators/version.py\", line '\n              '215, in migrate\\n'\n              '    raise VersionMigrationError(\\n'\n              'conda_forge_tick.migrators.version.VersionMigrationError: The '\n              'recipe did not change in the version migration, a URL did not '\n              'hash, or there is jinja2 syntax the bot cannot handle!\\n'\n              '\\n'\n              \"Please check the URLs in your recipe with version '2024.1' to \"\n              'make sure they exist!\\n'\n              '\\n'\n              'We also found the following errors:\\n'\n              '\\n'\n              ' - We found a problem parsing the recipe for version '\n              \"'2024.1': \\n\"\n              '\\n'\n              \"DuplicateKeyError('while constructing a mapping',   in \"\n              '\"<unicode string>\", line 29, column 3:\\n'\n              '      requires:\\n'\n              '      ^ (line: 29), \\'found duplicate key \"commands\" with value '\n              '\"[\\\\\\'cd test && python -m pytest\\\\\\']\" (original value: '\n              '\"[\\\\\\'pudb --help\\\\\\']\")\\',   in \"<unicode string>\", line 38, '\n              'column 3:\\n'\n              '      commands:\\n'\n              \"      ^ (line: 38), '\\\\n                    To suppress this \"\n              'check see:\\\\n                        '\n              'http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys\\\\n                    '\n              \"', '                    Duplicate keys will become an error in \"\n              'future releases, and are errors\\\\n                    by '\n              \"default when using the new API.\\\\n                    ')\\n\"\n              '\\n'\n              'traceback:\\n'\n              '  File '\n              '\"/opt/autotick-bot/conda_forge_tick/update_recipe/version.py\", '\n              'line 415, in update_version\\n'\n              '    cmeta = CondaMetaYAML(raw_meta_yaml)\\n'\n              '            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n'\n              '  File '\n              '\"/opt/autotick-bot/conda_forge_tick/recipe_parser/_parser.py\", '\n              'line 515, in __init__\\n'\n              '    self.meta = self._parser.load(\"\".join(lines))\\n'\n              '                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n'\n              '  File '\n              '\"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/ruamel/yaml/main.py\", '\n              'line 451, in load\\n'\n              '    return constructor.get_single_data()\\n'\n              '           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n'\n              '  File '\n              '\"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/ruamel/yaml/constructor.py\", '\n              'line 116, in get_single_data\\n'\n              '    return self.construct_document(node)\\n'\n              '           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n'\n              '  File '\n              '\"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/ruamel/yaml/constructor.py\", '\n              'line 125, in construct_document\\n'\n              '    for _dummy in generator:\\n'\n              '  File '\n              '\"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/ruamel/yaml/constructor.py\", '\n              'line 1476, in construct_yaml_map\\n'\n              '    self.construct_mapping(node, data, deep=True)\\n'\n              '  File '\n              '\"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/ruamel/yaml/constructor.py\", '\n              'line 1365, in construct_mapping\\n'\n              '    value = self.construct_object(value_node, deep=deep)\\n'\n              '            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n'\n              '  File '\n              '\"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/ruamel/yaml/constructor.py\", '\n              'line 147, in construct_object\\n'\n              '    data = self.construct_non_recursive_object(node)\\n'\n              '           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n'\n              '  File '\n              '\"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/ruamel/yaml/constructor.py\", '\n              'line 188, in construct_non_recursive_object\\n'\n              '    for _dummy in generator:\\n'\n              '  File '\n              '\"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/ruamel/yaml/constructor.py\", '\n              'line 1476, in construct_yaml_map\\n'\n              '    self.construct_mapping(node, data, deep=True)\\n'\n              '  File '\n              '\"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/ruamel/yaml/constructor.py\", '\n              'line 1366, in construct_mapping\\n'\n              '    if self.check_mapping_key(node, key_node, maptyp, key, '\n              'value):\\n'\n              '       '\n              '^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n'\n              '  File '\n              '\"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/ruamel/yaml/constructor.py\", '\n              'line 278, in check_mapping_key\\n'\n              '    raise DuplicateKeyError(*args)\\n'\n              '\\n'\n              '\\n'}\n"
 }
}