{
 "bad": false,
 "new_version": "6-33-01",
 "new_version_attempts": {
  "6-23-01": 2000,
  "6-25-01": 58,
  "6-25-02": 215,
  "6-26-00": 6,
  "6-26-02": 3,
  "6-26-04": 3,
  "6-26-06": 0,
  "6-26-08": 11,
  "6-26-10": 4,
  "6-29-01": 33,
  "6-31-01": 46,
  "6-33-01": 23
 },
 "new_version_errors": {
  "6-23-01": "We found a problem parsing the recipe for version '6-23-01': \n\nComposerError('expected a single document in the stream', <ruamel.yaml.error.StringMark object at 0x7f1c34acddd0>, 'but found another document', <ruamel.yaml.error.StringMark object at 0x7f1c471c2190>)\n\ntraceback:\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/migrators/version.py\", line 472, in migrate\n    cmeta = CondaMetaYAML(fp.read())\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/recipe_parser/_parser.py\", line 455, in __init__\n    self.meta = self._parser.load(\"\".join(lines))\n  File \"/usr/share/miniconda/envs/run_env/lib/python3.8/site-packages/ruamel/yaml/main.py\", line 343, in load\n    return constructor.get_single_data()\n  File \"/usr/share/miniconda/envs/run_env/lib/python3.8/site-packages/ruamel/yaml/constructor.py\", line 111, in get_single_data\n    node = self.composer.get_single_node()\n  File \"/usr/share/miniconda/envs/run_env/lib/python3.8/site-packages/ruamel/yaml/composer.py\", line 83, in get_single_node\n    raise ComposerError(\n",
  "6-25-01": "We found a problem parsing the recipe for version '6-25-01': \n\nComposerError('expected a single document in the stream', <ruamel.yaml.error.StringMark object at 0x7f09c06e3200>, 'but found another document', <ruamel.yaml.error.StringMark object at 0x7f09c0130ba0>)\n\ntraceback:\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/migrators/version.py\", line 472, in migrate\n    cmeta = CondaMetaYAML(fp.read())\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/recipe_parser/_parser.py\", line 455, in __init__\n    self.meta = self._parser.load(\"\".join(lines))\n  File \"/usr/share/miniconda/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/main.py\", line 343, in load\n    return constructor.get_single_data()\n  File \"/usr/share/miniconda/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 111, in get_single_data\n    node = self.composer.get_single_node()\n  File \"/usr/share/miniconda/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/composer.py\", line 83, in get_single_node\n    raise ComposerError(\n",
  "6-25-02": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '6-25-02' to make sure they exist!\n\nWe also found the following errors:\n\n - migrations do not work on versions not specified with jinja2\n",
  "6-26-00": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '6-26-00' to make sure they exist!\n\nWe also found the following errors:\n\n - migrations do not work on versions not specified with jinja2\n",
  "6-26-02": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '6-26-02' to make sure they exist!\n\nWe also found the following errors:\n\n - migrations do not work on versions not specified with jinja2\n",
  "6-26-04": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '6-26-04' to make sure they exist!\n\nWe also found the following errors:\n\n - migrations do not work on versions not specified with jinja2\n",
  "6-26-06": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '6-26-06' to make sure they exist!\n\nWe also found the following errors:\n\n - migrations do not work on versions not specified with jinja2\n",
  "6-26-08": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '6-26-08' to make sure they exist!\n\nWe also found the following errors:\n\n - migrations do not work on versions not specified with jinja2\n",
  "6-26-10": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '6-26-10' to make sure they exist!\n\nWe also found the following errors:\n\n - migrations do not work on versions not specified with jinja2\n",
  "6-29-01": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '6-29-01' to make sure they exist!\n\nWe also found the following errors:\n\n - migrations do not work on versions not specified with jinja2\n",
  "6-31-01": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '6-31-01' to make sure they exist!\n\nWe also found the following errors:\n\n - migrations do not work on versions not specified with jinja2\n",
  "6-33-01": "bot error (<a href=\"https://github.com/regro/cf-scripts/actions/runs/9260428437\">bot CI job</a>): main: Traceback (most recent call last):\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py\", line 567, in _run_migrator_on_feedstock_branch\n    migrator_uid, pr_json = run(\n                            ^^^^\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py\", line 215, in run\n    migration_run_data = run_migration(\n                         ^^^^^^^^^^^^^^\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/migration_runner.py\", line 63, in run_migration\n    return run_migration_containerized(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/migration_runner.py\", line 157, in run_migration_containerized\n    data = run_container_task(\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/utils.py\", line 249, in run_container_task\n    raise RuntimeError(\nRuntimeError: Error running migrate-feedstock in container - error KeyError('raw_meta_yaml') raised:\ncmd: ['docker',\n 'run',\n '-e',\n 'CF_TICK_IN_CONTAINER=true',\n '--security-opt=no-new-privileges',\n '--read-only',\n '--cap-drop=all',\n '--mount',\n 'type=tmpfs,destination=/tmp,tmpfs-mode=1777,tmpfs-size=6000000000',\n '-m',\n '6000m',\n '--cpus',\n '1',\n '--ulimit',\n 'nofile=1024:1024',\n '--ulimit',\n 'nproc=2048:2048',\n '--rm',\n '-i',\n '--mount',\n 'type=bind,source=/tmp/tmpa4_60mgb,destination=/cf_tick_dir',\n 'ghcr.io/regro/conda-forge-tick:master',\n '/opt/conda/envs/cf-scripts/bin/python',\n '-u',\n '/opt/autotick-bot/docker/run_bot_task.py',\n 'migrate-feedstock',\n '--feedstock-name',\n 'root',\n '--default-branch',\n 'main',\n '--existing-feedstock-node-attrs',\n '-',\n '--kwargs',\n '{\\n \"hash_type\": \"sha256\"\\n}',\n '--log-level',\n 'info']\nstdout: {'data': None,\n 'default_branch': 'main',\n 'error': \"KeyError('raw_meta_yaml')\",\n 'feedstock_name': 'root',\n 'input_kwargs': '{\\n \"hash_type\": \"sha256\"\\n}',\n 'traceback': 'Traceback (most recent call last):\\n'\n              '  File \"/opt/autotick-bot/docker/run_bot_task.py\", line 116, in '\n              '_run_bot_task\\n'\n              '    data = func(attrs=attrs, **kwargs)\\n'\n              '           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n'\n              '  File \"/opt/autotick-bot/docker/run_bot_task.py\", line 303, in '\n              '_migrate_feedstock\\n'\n              '    data = run_migration_local(\\n'\n              '           ^^^^^^^^^^^^^^^^^^^^\\n'\n              '  File '\n              '\"/opt/autotick-bot/conda_forge_tick/migration_runner.py\", line '\n              '235, in run_migration_local\\n'\n              '    migrator.run_pre_piggyback_migrations(recipe_dir, '\n              'feedstock_ctx.attrs, **kwargs)\\n'\n              '  File \"/opt/autotick-bot/conda_forge_tick/migrators/core.py\", '\n              'line 417, in run_pre_piggyback_migrations\\n'\n              '    if not mini_migrator.filter(attrs):\\n'\n              '           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n'\n              '  File '\n              '\"/opt/autotick-bot/conda_forge_tick/migrators/extra_jinj2a_keys_cleanup.py\", '\n              'line 34, in filter\\n'\n              '    raw_yaml = attrs[\"raw_meta_yaml\"]\\n'\n              '               ~~~~~^^^^^^^^^^^^^^^^^\\n'\n              '  File '\n              '\"/opt/autotick-bot/conda_forge_tick/lazy_json_backends.py\", '\n              'line 811, in __getitem__\\n'\n              '    return self._data[item]\\n'\n              '           ~~~~~~~~~~^^^^^^\\n'\n              \"KeyError: 'raw_meta_yaml'\\n\"}\n"
 }
}