{
 "bad": false,
 "new_version": "6-33-01",
 "new_version_attempts": {
  "6-23-01": 2000,
  "6-25-01": 58,
  "6-25-02": 215,
  "6-26-00": 6,
  "6-26-02": 3,
  "6-26-04": 3,
  "6-26-06": 0,
  "6-26-08": 11,
  "6-26-10": 4,
  "6-29-01": 33,
  "6-31-01": 46,
  "6-33-01": 17
 },
 "new_version_errors": {
  "6-23-01": "We found a problem parsing the recipe for version '6-23-01': \n\nComposerError('expected a single document in the stream', <ruamel.yaml.error.StringMark object at 0x7f1c34acddd0>, 'but found another document', <ruamel.yaml.error.StringMark object at 0x7f1c471c2190>)\n\ntraceback:\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/migrators/version.py\", line 472, in migrate\n    cmeta = CondaMetaYAML(fp.read())\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/recipe_parser/_parser.py\", line 455, in __init__\n    self.meta = self._parser.load(\"\".join(lines))\n  File \"/usr/share/miniconda/envs/run_env/lib/python3.8/site-packages/ruamel/yaml/main.py\", line 343, in load\n    return constructor.get_single_data()\n  File \"/usr/share/miniconda/envs/run_env/lib/python3.8/site-packages/ruamel/yaml/constructor.py\", line 111, in get_single_data\n    node = self.composer.get_single_node()\n  File \"/usr/share/miniconda/envs/run_env/lib/python3.8/site-packages/ruamel/yaml/composer.py\", line 83, in get_single_node\n    raise ComposerError(\n",
  "6-25-01": "We found a problem parsing the recipe for version '6-25-01': \n\nComposerError('expected a single document in the stream', <ruamel.yaml.error.StringMark object at 0x7f09c06e3200>, 'but found another document', <ruamel.yaml.error.StringMark object at 0x7f09c0130ba0>)\n\ntraceback:\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/migrators/version.py\", line 472, in migrate\n    cmeta = CondaMetaYAML(fp.read())\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/recipe_parser/_parser.py\", line 455, in __init__\n    self.meta = self._parser.load(\"\".join(lines))\n  File \"/usr/share/miniconda/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/main.py\", line 343, in load\n    return constructor.get_single_data()\n  File \"/usr/share/miniconda/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 111, in get_single_data\n    node = self.composer.get_single_node()\n  File \"/usr/share/miniconda/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/composer.py\", line 83, in get_single_node\n    raise ComposerError(\n",
  "6-25-02": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '6-25-02' to make sure they exist!\n\nWe also found the following errors:\n\n - migrations do not work on versions not specified with jinja2\n",
  "6-26-00": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '6-26-00' to make sure they exist!\n\nWe also found the following errors:\n\n - migrations do not work on versions not specified with jinja2\n",
  "6-26-02": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '6-26-02' to make sure they exist!\n\nWe also found the following errors:\n\n - migrations do not work on versions not specified with jinja2\n",
  "6-26-04": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '6-26-04' to make sure they exist!\n\nWe also found the following errors:\n\n - migrations do not work on versions not specified with jinja2\n",
  "6-26-06": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '6-26-06' to make sure they exist!\n\nWe also found the following errors:\n\n - migrations do not work on versions not specified with jinja2\n",
  "6-26-08": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '6-26-08' to make sure they exist!\n\nWe also found the following errors:\n\n - migrations do not work on versions not specified with jinja2\n",
  "6-26-10": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '6-26-10' to make sure they exist!\n\nWe also found the following errors:\n\n - migrations do not work on versions not specified with jinja2\n",
  "6-29-01": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '6-29-01' to make sure they exist!\n\nWe also found the following errors:\n\n - migrations do not work on versions not specified with jinja2\n",
  "6-31-01": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '6-31-01' to make sure they exist!\n\nWe also found the following errors:\n\n - migrations do not work on versions not specified with jinja2\n",
  "6-33-01": "bot error (<a href=\"https://github.com/regro/cf-scripts/actions/runs/9229528244\">bot CI job</a>): main: Traceback (most recent call last):\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py\", line 567, in _run_migrator_on_feedstock_branch\n    migrator_uid, pr_json = run(\n                            ^^^^\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py\", line 214, in run\n    migration_run_data = run_migration(\n                         ^^^^^^^^^^^^^^\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/migration_runner.py\", line 35, in run_migration\n    return run_migration_local(\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/migration_runner.py\", line 132, in run_migration_local\n    migrator.run_pre_piggyback_migrations(recipe_dir, feedstock_ctx.attrs, **kwargs)\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/migrators/core.py\", line 418, in run_pre_piggyback_migrations\n    mini_migrator.migrate(recipe_dir, attrs, **kwargs)\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/migrators/cstdlib.py\", line 213, in migrate\n    sections = _slice_into_output_sections(lines, attrs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/migrators/libboost.py\", line 105, in _slice_into_output_sections\n    raise RuntimeError(\nRuntimeError: Could not find all output sections in meta.yaml! Found 5 sections for outputs names = {'root_base', 'root'}.\n"
 }
}