{
  "_feedstock_status": {
    "acctaudem": {
      "immediate_children": [],
      "num_descendants": 0,
      "pr_status": "clean",
      "pr_url": "https://github.com/conda-forge/acctaudem-feedstock/pull/13",
      "pre_pr_migrator_status": ""
    },
    "autorift": {
      "immediate_children": [],
      "num_descendants": 0,
      "pr_status": "unstable",
      "pr_url": "https://github.com/conda-forge/autorift-feedstock/pull/49",
      "pre_pr_migrator_status": ""
    },
    "dggrid": {
      "immediate_children": [],
      "num_descendants": 0,
      "pr_status": "clean",
      "pr_url": "https://github.com/conda-forge/dggrid-feedstock/pull/5",
      "pre_pr_migrator_status": ""
    },
    "exactextract": {
      "immediate_children": [],
      "num_descendants": 0,
      "pr_status": "",
      "pr_url": "https://github.com/conda-forge/exactextract-feedstock",
      "pre_pr_migrator_status": ""
    },
    "fiona": {
      "immediate_children": [],
      "num_descendants": 0,
      "pre_pr_migrator_status": "not solvable (<a href='https://github.com/regro/cf-scripts/actions/runs/9165102266'>bot CI job</a>) @ main\n                <details>\n                <div align=\"left\">\n                <pre>\n                linux_ppc64le_numpy1.22python3.8.____cpython: Could not solve for environment specs\nThe following package could not be installed\n\u2514\u2500 libgdal 3.9.*  does not exist (perhaps a typo or a missing channel).</pre><pre>linux_ppc64le_numpy2.0python3.10.____cpython: Could not solve for environment specs\nThe following package could not be installed\n\u2514\u2500 libgdal 3.9.*  does not exist (perhaps a typo or a missing channel).</pre><pre>linux_ppc64le_numpy2.0python3.11.____cpython: Could not solve for environment specs\nThe following package could not be installed\n\u2514\u2500 libgdal 3.9.*  does not exist (perhaps a typo or a missing channel).</pre><pre>linux_ppc64le_numpy2.0python3.12.____cpython: Could not solve for environment specs\nThe following package could not be installed\n\u2514\u2500 libgdal 3.9.*  does not exist (perhaps a typo or a missing channel).</pre><pre>linux_ppc64le_numpy2.0python3.9.____cpython: Could not solve for environment specs\nThe following package could not be installed\n\u2514\u2500 libgdal 3.9.*  does not exist (perhaps a typo or a missing channel).\n                </pre>\n                </div>\n                </details>"
    },
    "gazebo": {
      "immediate_children": [],
      "num_descendants": 0,
      "pr_status": "",
      "pr_url": "https://github.com/conda-forge/gazebo-feedstock",
      "pre_pr_migrator_status": ""
    },
    "gdal-csharp": {
      "immediate_children": [],
      "num_descendants": 0,
      "pr_status": "",
      "pr_url": "https://github.com/conda-forge/gdal-csharp-feedstock",
      "pre_pr_migrator_status": ""
    },
    "gmt": {
      "immediate_children": [],
      "num_descendants": 0,
      "pre_pr_migrator_status": "not solvable (<a href='https://github.com/regro/cf-scripts/actions/runs/9171873269'>bot CI job</a>) @ main\n                <details>\n                <div align=\"left\">\n                <pre>\n                linux_ppc64le_: Could not solve for environment specs\nThe following package could not be installed\n\u2514\u2500 gdal 3.9.*  does not exist (perhaps a typo or a missing channel).\n                </pre>\n                </div>\n                </details>"
    },
    "gz-common": {
      "immediate_children": [],
      "num_descendants": 0,
      "pre_pr_migrator_status": "not solvable (<a href='https://github.com/regro/cf-scripts/actions/runs/9163689719'>bot CI job</a>) @ main\n                <details>\n                <div align=\"left\">\n                <pre>\n                linux_ppc64le_ffmpeg6: Could not solve for environment specs\nThe following package could not be installed\n\u2514\u2500 libgdal 3.9.*  does not exist (perhaps a typo or a missing channel).</pre><pre>linux_ppc64le_ffmpeg7: Could not solve for environment specs\nThe following package could not be installed\n\u2514\u2500 libgdal 3.9.*  does not exist (perhaps a typo or a missing channel).\n                </pre>\n                </div>\n                </details>"
    },
    "heavydb-ext": {
      "immediate_children": [
        "omniscidb"
      ],
      "num_descendants": 1,
      "pr_status": "unstable",
      "pr_url": "https://github.com/conda-forge/heavydb-ext-feedstock/pull/72",
      "pre_pr_migrator_status": ""
    },
    "helios": {
      "immediate_children": [],
      "num_descendants": 0,
      "pr_status": "",
      "pr_url": "https://github.com/conda-forge/helios-feedstock",
      "pre_pr_migrator_status": ""
    },
    "hexer": {
      "immediate_children": [],
      "num_descendants": 0,
      "pr_status": "clean",
      "pr_url": "https://github.com/conda-forge/hexer-feedstock/pull/14",
      "pre_pr_migrator_status": ""
    },
    "isce2": {
      "immediate_children": [],
      "num_descendants": 0,
      "pr_status": "unstable",
      "pr_url": "https://github.com/conda-forge/isce2-feedstock/pull/68",
      "pre_pr_migrator_status": ""
    },
    "isce3": {
      "immediate_children": [],
      "num_descendants": 0,
      "pr_status": "unstable",
      "pr_url": "https://github.com/conda-forge/isce3-feedstock/pull/61",
      "pre_pr_migrator_status": ""
    },
    "lue": {
      "immediate_children": [],
      "num_descendants": 0,
      "pr_status": "unstable",
      "pr_url": "https://github.com/conda-forge/lue-feedstock/pull/47",
      "pre_pr_migrator_status": ""
    },
    "mapserver": {
      "immediate_children": [],
      "num_descendants": 0,
      "pr_status": "unknown",
      "pr_url": "https://github.com/conda-forge/mapserver-feedstock/pull/45",
      "pre_pr_migrator_status": ""
    },
    "mdal": {
      "immediate_children": [],
      "num_descendants": 0,
      "pr_status": "",
      "pr_url": "https://github.com/conda-forge/mdal-feedstock",
      "pre_pr_migrator_status": ""
    },
    "mesher": {
      "immediate_children": [],
      "num_descendants": 0,
      "pr_status": "",
      "pr_url": "https://github.com/conda-forge/mesher-feedstock",
      "pre_pr_migrator_status": ""
    },
    "nansat": {
      "immediate_children": [],
      "num_descendants": 0,
      "pr_status": "unstable",
      "pr_url": "https://github.com/conda-forge/nansat-feedstock/pull/40",
      "pre_pr_migrator_status": ""
    },
    "ncl": {
      "immediate_children": [],
      "num_descendants": 0,
      "pr_status": "",
      "pr_url": "https://github.com/conda-forge/ncl-feedstock",
      "pre_pr_migrator_status": ""
    },
    "pcraster": {
      "immediate_children": [],
      "num_descendants": 0,
      "pr_status": "",
      "pr_url": "https://github.com/conda-forge/pcraster-feedstock",
      "pre_pr_migrator_status": ""
    },
    "pdal": {
      "immediate_children": [
        "pdal_wrench",
        "qgis"
      ],
      "num_descendants": 2,
      "pr_status": "",
      "pr_url": "https://github.com/conda-forge/pdal-feedstock",
      "pre_pr_migrator_status": ""
    },
    "pdal_wrench": {
      "immediate_children": [],
      "num_descendants": 0,
      "pr_status": "clean",
      "pr_url": "https://github.com/conda-forge/pdal_wrench-feedstock/pull/4",
      "pre_pr_migrator_status": ""
    },
    "postgis": {
      "immediate_children": [],
      "num_descendants": 0,
      "pr_status": "",
      "pr_url": "https://github.com/conda-forge/postgis-feedstock",
      "pre_pr_migrator_status": ""
    },
    "pycoalescence": {
      "immediate_children": [],
      "num_descendants": 0,
      "pr_status": "unstable",
      "pr_url": "https://github.com/conda-forge/pycoalescence-feedstock/pull/59",
      "pre_pr_migrator_status": ""
    },
    "pygplates": {
      "immediate_children": [],
      "num_descendants": 0,
      "pre_pr_migrator_status": "not solvable (<a href='https://github.com/regro/cf-scripts/actions/runs/9167242221'>bot CI job</a>) @ main\n                <details>\n                <div align=\"left\">\n                <pre>\n                linux_64_numpy1.22python3.10.____cpython: Could not solve for environment specs\nThe following packages are incompatible\n\u251C\u2500 libgdal 3.9.*  is installable and it requires\n\u2502  \u2514\u2500 proj >=9.4.0,<9.4.1.0a0 , which can be installed;\n\u2514\u2500 proj 9.3.1.*  is not installable because it conflicts with any installable versions previously reported.</pre><pre>linux_64_numpy1.22python3.8.____cpython: Could not solve for environment specs\nThe following packages are incompatible\n\u251C\u2500 libgdal 3.9.*  is installable and it requires\n\u2502  \u2514\u2500 proj >=9.4.0,<9.4.1.0a0 , which can be installed;\n\u2514\u2500 proj 9.3.1.*  is not installable because it conflicts with any installable versions previously reported.</pre><pre>linux_64_numpy1.22python3.9.____cpython: Could not solve for environment specs\nThe following packages are incompatible\n\u251C\u2500 libgdal 3.9.*  is installable and it requires\n\u2502  \u2514\u2500 proj >=9.4.0,<9.4.1.0a0 , which can be installed;\n\u2514\u2500 proj 9.3.1.*  is not installable because it conflicts with any installable versions previously reported.</pre><pre>linux_64_numpy1.23python3.11.____cpython: Could not solve for environment specs\nThe following packages are incompatible\n\u251C\u2500 libgdal 3.9.*  is installable and it requires\n\u2502  \u2514\u2500 proj >=9.4.0,<9.4.1.0a0 , which can be installed;\n\u2514\u2500 proj 9.3.1.*  is not installable because it conflicts with any installable versions previously reported.</pre><pre>linux_64_numpy1.26python3.12.____cpython: Could not solve for environment specs\nThe following packages are incompatible\n\u251C\u2500 libgdal 3.9.*  is installable and it requires\n\u2502  \u2514\u2500 proj >=9.4.0,<9.4.1.0a0 , which can be installed;\n\u2514\u2500 proj 9.3.1.*  is not installable because it conflicts with any installable versions previously reported.</pre><pre>linux_aarch64_numpy1.22python3.10.____cpython: Could not solve for environment specs\nThe following packages are incompatible\n\u251C\u2500 libgdal 3.9.*  is installable and it requires\n\u2502  \u2514\u2500 proj >=9.4.0,<9.4.1.0a0 , which can be installed;\n\u2514\u2500 proj 9.3.1.*  is not installable because it conflicts with any installable versions previously reported.</pre><pre>linux_aarch64_numpy1.22python3.8.____cpython: Could not solve for environment specs\nThe following packages are incompatible\n\u251C\u2500 libgdal 3.9.*  is installable and it requires\n\u2502  \u2514\u2500 proj >=9.4.0,<9.4.1.0a0 , which can be installed;\n\u2514\u2500 proj 9.3.1.*  is not installable because it conflicts with any installable versions previously reported.</pre><pre>linux_aarch64_numpy1.22python3.9.____cpython: Could not solve for environment specs\nThe following packages are incompatible\n\u251C\u2500 libgdal 3.9.*  is installable and it requires\n\u2502  \u2514\u2500 proj >=9.4.0,<9.4.1.0a0 , which can be installed;\n\u2514\u2500 proj 9.3.1.*  is not installable because it conflicts with any installable versions previously reported.</pre><pre>linux_aarch64_numpy1.23python3.11.____cpython: Could not solve for environment specs\nThe following packages are incompatible\n\u251C\u2500 libgdal 3.9.*  is installable and it requires\n\u2502  \u2514\u2500 proj >=9.4.0,<9.4.1.0a0 , which can be installed;\n\u2514\u2500 proj 9.3.1.*  is not installable because it conflicts with any installable versions previously reported.</pre><pre>linux_aarch64_numpy1.26python3.12.____cpython: Could not solve for environment specs\nThe following packages are incompatible\n\u251C\u2500 libgdal 3.9.*  is installable and it requires\n\u2502  \u2514\u2500 proj >=9.4.0,<9.4.1.0a0 , which can be installed;\n\u2514\u2500 proj 9.3.1.*  is not installable because it conflicts with any installable versions previously reported.</pre><pre>linux_ppc64le_numpy1.22python3.10.____cpython: Could not solve for environment specs\nThe following package could not be installed\n\u2514\u2500 libgdal 3.9.*  does not exist (perhaps a typo or a missing channel).</pre><pre>linux_ppc64le_numpy1.22python3.8.____cpython: Could not solve for environment specs\nThe following package could not be installed\n\u2514\u2500 libgdal 3.9.*  does not exist (perhaps a typo or a missing channel).</pre><pre>linux_ppc64le_numpy1.22python3.9.____cpython: Could not solve for environment specs\nThe following package could not be installed\n\u2514\u2500 libgdal 3.9.*  does not exist (perhaps a typo or a missing channel).</pre><pre>linux_ppc64le_numpy1.23python3.11.____cpython: Could not solve for environment specs\nThe following package could not be installed\n\u2514\u2500 libgdal 3.9.*  does not exist (perhaps a typo or a missing channel).</pre><pre>linux_ppc64le_numpy1.26python3.12.____cpython: Could not solve for environment specs\nThe following package could not be installed\n\u2514\u2500 libgdal 3.9.*  does not exist (perhaps a typo or a missing channel).</pre><pre>osx_64_numpy1.22python3.10.____cpython: Could not solve for environment specs\nThe following packages are incompatible\n\u251C\u2500 libgdal 3.9.*  is installable and it requires\n\u2502  \u2514\u2500 proj >=9.4.0,<9.4.1.0a0 , which can be installed;\n\u2514\u2500 proj 9.3.1.*  is not installable because it conflicts with any installable versions previously reported.</pre><pre>osx_64_numpy1.22python3.8.____cpython: Could not solve for environment specs\nThe following packages are incompatible\n\u251C\u2500 libgdal 3.9.*  is installable and it requires\n\u2502  \u2514\u2500 proj >=9.4.0,<9.4.1.0a0 , which can be installed;\n\u2514\u2500 proj 9.3.1.*  is not installable because it conflicts with any installable versions previously reported.</pre><pre>osx_64_numpy1.22python3.9.____cpython: Could not solve for environment specs\nThe following packages are incompatible\n\u251C\u2500 libgdal 3.9.*  is installable and it requires\n\u2502  \u2514\u2500 proj >=9.4.0,<9.4.1.0a0 , which can be installed;\n\u2514\u2500 proj 9.3.1.*  is not installable because it conflicts with any installable versions previously reported.</pre><pre>osx_64_numpy1.23python3.11.____cpython: Could not solve for environment specs\nThe following packages are incompatible\n\u251C\u2500 libgdal 3.9.*  is installable and it requires\n\u2502  \u2514\u2500 proj >=9.4.0,<9.4.1.0a0 , which can be installed;\n\u2514\u2500 proj 9.3.1.*  is not installable because it conflicts with any installable versions previously reported.</pre><pre>osx_64_numpy1.26python3.12.____cpython: Could not solve for environment specs\nThe following packages are incompatible\n\u251C\u2500 libgdal 3.9.*  is installable and it requires\n\u2502  \u2514\u2500 proj >=9.4.0,<9.4.1.0a0 , which can be installed;\n\u2514\u2500 proj 9.3.1.*  is not installable because it conflicts with any installable versions previously reported.</pre><pre>osx_arm64_numpy1.22python3.10.____cpython: Could not solve for environment specs\nThe following packages are incompatible\n\u251C\u2500 libgdal 3.9.*  is installable and it requires\n\u2502  \u2514\u2500 proj >=9.4.0,<9.4.1.0a0 , which can be installed;\n\u2514\u2500 proj 9.3.1.*  is not installable because it conflicts with any installable versions previously reported.</pre><pre>osx_arm64_numpy1.22python3.8.____cpython: Could not solve for environment specs\nThe following packages are incompatible\n\u251C\u2500 libgdal 3.9.*  is installable and it requires\n\u2502  \u2514\u2500 proj >=9.4.0,<9.4.1.0a0 , which can be installed;\n\u2514\u2500 proj 9.3.1.*  is not installable because it conflicts with any installable versions previously reported.</pre><pre>osx_arm64_numpy1.22python3.9.____cpython: Could not solve for environment specs\nThe following packages are incompatible\n\u251C\u2500 libgdal 3.9.*  is installable and it requires\n\u2502  \u2514\u2500 proj >=9.4.0,<9.4.1.0a0 , which can be installed;\n\u2514\u2500 proj 9.3.1.*  is not installable because it conflicts with any installable versions previously reported.</pre><pre>osx_arm64_numpy1.23python3.11.____cpython: Could not solve for environment specs\nThe following packages are incompatible\n\u251C\u2500 libgdal 3.9.*  is installable and it requires\n\u2502  \u2514\u2500 proj >=9.4.0,<9.4.1.0a0 , which can be installed;\n\u2514\u2500 proj 9.3.1.*  is not installable because it conflicts with any installable versions previously reported.</pre><pre>osx_arm64_numpy1.26python3.12.____cpython: Could not solve for environment specs\nThe following packages are incompatible\n\u251C\u2500 libgdal 3.9.*  is installable and it requires\n\u2502  \u2514\u2500 proj >=9.4.0,<9.4.1.0a0 , which can be installed;\n\u2514\u2500 proj 9.3.1.*  is not installable because it conflicts with any installable versions previously reported.</pre><pre>win_64_numpy1.22python3.10.____cpython: Could not solve for environment specs\nThe following packages are incompatible\n\u251C\u2500 libgdal 3.9.*  is installable and it requires\n\u2502  \u2514\u2500 proj >=9.4.0,<9.4.1.0a0 , which can be installed;\n\u2514\u2500 proj 9.3.1.*  is not installable because it conflicts with any installable versions previously reported.</pre><pre>win_64_numpy1.22python3.8.____cpython: Could not solve for environment specs\nThe following packages are incompatible\n\u251C\u2500 libgdal 3.9.*  is installable and it requires\n\u2502  \u2514\u2500 proj >=9.4.0,<9.4.1.0a0 , which can be installed;\n\u2514\u2500 proj 9.3.1.*  is not installable because it conflicts with any installable versions previously reported.</pre><pre>win_64_numpy1.22python3.9.____cpython: Could not solve for environment specs\nThe following packages are incompatible\n\u251C\u2500 libgdal 3.9.*  is installable and it requires\n\u2502  \u2514\u2500 proj >=9.4.0,<9.4.1.0a0 , which can be installed;\n\u2514\u2500 proj 9.3.1.*  is not installable because it conflicts with any installable versions previously reported.</pre><pre>win_64_numpy1.23python3.11.____cpython: Could not solve for environment specs\nThe following packages are incompatible\n\u251C\u2500 libgdal 3.9.*  is installable and it requires\n\u2502  \u2514\u2500 proj >=9.4.0,<9.4.1.0a0 , which can be installed;\n\u2514\u2500 proj 9.3.1.*  is not installable because it conflicts with any installable versions previously reported.</pre><pre>win_64_numpy1.26python3.12.____cpython: Could not solve for environment specs\nThe following packages are incompatible\n\u251C\u2500 libgdal 3.9.*  is installable and it requires\n\u2502  \u2514\u2500 proj >=9.4.0,<9.4.1.0a0 , which can be installed;\n\u2514\u2500 proj 9.3.1.*  is not installable because it conflicts with any installable versions previously reported.\n                </pre>\n                </div>\n                </details>"
    },
    "pyogrio": {
      "immediate_children": [],
      "num_descendants": 0,
      "pr_status": "unknown",
      "pr_url": "https://github.com/conda-forge/pyogrio-feedstock/pull/46",
      "pre_pr_migrator_status": ""
    },
    "qgis": {
      "immediate_children": [],
      "num_descendants": 0,
      "pr_status": "unstable",
      "pr_url": "https://github.com/conda-forge/qgis-feedstock/pull/434",
      "pre_pr_migrator_status": ""
    },
    "r-gdalcubes": {
      "immediate_children": [],
      "num_descendants": 0,
      "pr_status": "",
      "pr_url": "https://github.com/conda-forge/r-gdalcubes-feedstock",
      "pre_pr_migrator_status": ""
    },
    "r-rgdal": {
      "immediate_children": [],
      "num_descendants": 0,
      "pre_pr_migrator_status": "not solvable (<a href='https://github.com/regro/cf-scripts/actions/runs/9171873269'>bot CI job</a>) @ main\n                <details>\n                <div align=\"left\">\n                <pre>\n                linux_ppc64le_r_base4.2: Could not solve for environment specs\nThe following packages are incompatible\n\u251C\u2500 libgdal 3.9.*  does not exist (perhaps a typo or a missing channel);\n\u2514\u2500 proj 9.4.0.*  does not exist (perhaps a typo or a missing channel).</pre><pre>linux_ppc64le_r_base4.3: Could not solve for environment specs\nThe following packages are incompatible\n\u251C\u2500 libgdal 3.9.*  does not exist (perhaps a typo or a missing channel);\n\u2514\u2500 proj 9.4.0.*  does not exist (perhaps a typo or a missing channel).\n                </pre>\n                </div>\n                </details>"
    },
    "r-sf": {
      "immediate_children": [],
      "num_descendants": 0,
      "pre_pr_migrator_status": "not solvable (<a href='https://github.com/regro/cf-scripts/actions/runs/9167242221'>bot CI job</a>) @ main\n                <details>\n                <div align=\"left\">\n                <pre>\n                linux_ppc64le_r_base4.2: Could not solve for environment specs\nThe following packages are incompatible\n\u251C\u2500 libgdal 3.9.*  does not exist (perhaps a typo or a missing channel);\n\u2514\u2500 proj 9.4.0.*  does not exist (perhaps a typo or a missing channel).</pre><pre>linux_ppc64le_r_base4.3: Could not solve for environment specs\nThe following packages are incompatible\n\u251C\u2500 libgdal 3.9.*  does not exist (perhaps a typo or a missing channel);\n\u2514\u2500 proj 9.4.0.*  does not exist (perhaps a typo or a missing channel).\n                </pre>\n                </div>\n                </details>"
    },
    "r-terra": {
      "immediate_children": [],
      "num_descendants": 0,
      "pre_pr_migrator_status": "bot error (<a href=\"https://github.com/regro/cf-scripts/actions/runs/9171873269\">bot CI job</a>): main: Traceback (most recent call last):\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py\", line 567, in _run_migrator_on_feedstock_branch\n    migrator_uid, pr_json = run(\n                            ^^^^\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py\", line 259, in run\n    rerender_msg = rerender_feedstock(feedstock_dir, timeout=900)\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/rerender_feedstock.py\", line 49, in rerender_feedstock\n    return rerender_feedstock_containerized(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/rerender_feedstock.py\", line 102, in rerender_feedstock_containerized\n    data = run_container_task(\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/utils.py\", line 249, in run_container_task\n    raise RuntimeError(\nRuntimeError: Error running rerender-feedstock in container - error RuntimeError('Failed to rerender.\\noutput: INFO:conda_smithy.configure_feedstock:Downloading conda-forge-pinning-2024.05.21.08.49.41\\nTraceback (most recent call last):\\n  File \"/opt/conda/envs/cf-scripts/bin/conda-smithy\", line 10, in <module>\\n    sys.exit(main())\\n             ^^^^^^\\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/cli.py\", line 737, in main\\n    args.subcommand_func(args)\\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/cli.py\", line 586, in __call__\\n    self._call(args, args.temporary_directory)\\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/cli.py\", line 589, in _call\\n    configure_feedstock.main(\\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/configure_feedstock.py\", line 2714, in main\\n    exclusive_config_file, cf_pinning_ver = get_cached_cfp_file_path(\\n                                            ^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/configure_feedstock.py\", line 2535, in get_cached_cfp_file_path\\n    get_cfp_file_path(smithy_cache)\\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/configure_feedstock.py\", line 2476, in get_cfp_file_path\\n    response.raise_for_status()\\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/requests/models.py\", line 1024, in raise_for_status\\n    raise HTTPError(http_error_msg, response=self)\\nrequests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: https://api.anaconda.org/download/conda-forge/conda-forge-pinning/2024.05.21.08.49.41/noarch/conda-forge-pinning-2024.05.21.08.49.41-hd8ed1ab_0.conda\\n\\n') raised:\ncmd: ['docker',\n 'run',\n '-e',\n 'CF_TICK_IN_CONTAINER=true',\n '--security-opt=no-new-privileges',\n '--read-only',\n '--cap-drop=all',\n '--mount',\n 'type=tmpfs,destination=/tmp,tmpfs-mode=1777,tmpfs-size=6000000000',\n '-m',\n '6000m',\n '--cpus',\n '1',\n '--ulimit',\n 'nofile=1024:1024',\n '--ulimit',\n 'nproc=2048:2048',\n '--rm',\n '-i',\n '--mount',\n 'type=bind,source=/tmp/tmpahv7_k3b,destination=/cf_tick_dir',\n 'ghcr.io/regro/conda-forge-tick:master',\n '/opt/conda/envs/cf-scripts/bin/python',\n '-u',\n '/opt/autotick-bot/docker/run_bot_task.py',\n 'rerender-feedstock',\n '--timeout',\n '900',\n '--log-level',\n 'info']\nstdout: {'data': None,\n 'error': \"RuntimeError('Failed to rerender.\\\\noutput: \"\n          'INFO:conda_smithy.configure_feedstock:Downloading '\n          'conda-forge-pinning-2024.05.21.08.49.41\\\\nTraceback (most recent '\n          'call last):\\\\n  File \"/opt/conda/envs/cf-scripts/bin/conda-smithy\", '\n          'line 10, in <module>\\\\n    sys.exit(main())\\\\n             '\n          '^^^^^^\\\\n  File '\n          '\"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/cli.py\", '\n          'line 737, in main\\\\n    args.subcommand_func(args)\\\\n  File '\n          '\"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/cli.py\", '\n          'line 586, in __call__\\\\n    self._call(args, '\n          'args.temporary_directory)\\\\n  File '\n          '\"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/cli.py\", '\n          'line 589, in _call\\\\n    configure_feedstock.main(\\\\n  File '\n          '\"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/configure_feedstock.py\", '\n          'line 2714, in main\\\\n    exclusive_config_file, cf_pinning_ver = '\n          'get_cached_cfp_file_path(\\\\n                                            '\n          '^^^^^^^^^^^^^^^^^^^^^^^^^\\\\n  File '\n          '\"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/configure_feedstock.py\", '\n          'line 2535, in get_cached_cfp_file_path\\\\n    '\n          'get_cfp_file_path(smithy_cache)\\\\n  File '\n          '\"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/configure_feedstock.py\", '\n          'line 2476, in get_cfp_file_path\\\\n    '\n          'response.raise_for_status()\\\\n  File '\n          '\"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/requests/models.py\", '\n          'line 1024, in raise_for_status\\\\n    raise '\n          'HTTPError(http_error_msg, '\n          'response=self)\\\\nrequests.exceptions.HTTPError: 503 Server Error: '\n          'Service Unavailable for url: '\n          \"https://api.anaconda.org/download/conda-forge/conda-forge-pinning/2024.05.21.08.49.41/noarch/conda-forge-pinning-2024.05.21.08.49.41-hd8ed1ab_0.conda\\\\n\\\\n')\",\n 'timeout': 900,\n 'traceback': 'Traceback (most recent call last):\\n'\n              '  File \"/opt/autotick-bot/docker/run_bot_task.py\", line 118, in '\n              '_run_bot_task\\n'\n              '    data = func(**kwargs)\\n'\n              '           ^^^^^^^^^^^^^^\\n'\n              '  File \"/opt/autotick-bot/docker/run_bot_task.py\", line 239, in '\n              '_rerender_feedstock\\n'\n              '    msg = rerender_feedstock_local(fs_dir, **kwargs)\\n'\n              '          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n'\n              '  File '\n              '\"/opt/autotick-bot/conda_forge_tick/rerender_feedstock.py\", '\n              'line 239, in rerender_feedstock_local\\n'\n              '    raise RuntimeError(f\"Failed to rerender.\\\\noutput: '\n              '{ret.stdout}\\\\n\")\\n'\n              'RuntimeError: Failed to rerender.\\n'\n              'output: INFO:conda_smithy.configure_feedstock:Downloading '\n              'conda-forge-pinning-2024.05.21.08.49.41\\n'\n              'Traceback (most recent call last):\\n'\n              '  File \"/opt/conda/envs/cf-scripts/bin/conda-smithy\", line 10, '\n              'in <module>\\n'\n              '    sys.exit(main())\\n'\n              '             ^^^^^^\\n'\n              '  File '\n              '\"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/cli.py\", '\n              'line 737, in main\\n'\n              '    args.subcommand_func(args)\\n'\n              '  File '\n              '\"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/cli.py\", '\n              'line 586, in __call__\\n'\n              '    self._call(args, args.temporary_directory)\\n'\n              '  File '\n              '\"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/cli.py\", '\n              'line 589, in _call\\n'\n              '    configure_feedstock.main(\\n'\n              '  File '\n              '\"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/configure_feedstock.py\", '\n              'line 2714, in main\\n'\n              '    exclusive_config_file, cf_pinning_ver = '\n              'get_cached_cfp_file_path(\\n'\n              '                                            '\n              '^^^^^^^^^^^^^^^^^^^^^^^^^\\n'\n              '  File '\n              '\"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/configure_feedstock.py\", '\n              'line 2535, in get_cached_cfp_file_path\\n'\n              '    get_cfp_file_path(smithy_cache)\\n'\n              '  File '\n              '\"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/configure_feedstock.py\", '\n              'line 2476, in get_cfp_file_path\\n'\n              '    response.raise_for_status()\\n'\n              '  File '\n              '\"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/requests/models.py\", '\n              'line 1024, in raise_for_status\\n'\n              '    raise HTTPError(http_error_msg, response=self)\\n'\n              'requests.exceptions.HTTPError: 503 Server Error: Service '\n              'Unavailable for url: '\n              'https://api.anaconda.org/download/conda-forge/conda-forge-pinning/2024.05.21.08.49.41/noarch/conda-forge-pinning-2024.05.21.08.49.41-hd8ed1ab_0.conda\\n'\n              '\\n'\n              '\\n'}\n"
    },
    "rasam": {
      "immediate_children": [],
      "num_descendants": 0,
      "pr_status": "clean",
      "pr_url": "https://github.com/conda-forge/rasam-feedstock/pull/2",
      "pre_pr_migrator_status": ""
    },
    "rasterio": {
      "immediate_children": [],
      "num_descendants": 0,
      "pre_pr_migrator_status": "not solvable (<a href='https://github.com/regro/cf-scripts/actions/runs/9166281037'>bot CI job</a>) @ main\n                <details>\n                <div align=\"left\">\n                <pre>\n                linux_ppc64le_numpy1.22python3.10.____cpython: Could not solve for environment specs\nThe following packages are incompatible\n\u251C\u2500 libgdal 3.9.*  does not exist (perhaps a typo or a missing channel);\n\u2514\u2500 proj 9.4.0.*  does not exist (perhaps a typo or a missing channel).</pre><pre>linux_ppc64le_numpy1.22python3.8.____cpython: Could not solve for environment specs\nThe following packages are incompatible\n\u251C\u2500 libgdal 3.9.*  does not exist (perhaps a typo or a missing channel);\n\u2514\u2500 proj 9.4.0.*  does not exist (perhaps a typo or a missing channel).</pre><pre>linux_ppc64le_numpy1.22python3.9.____cpython: Could not solve for environment specs\nThe following packages are incompatible\n\u251C\u2500 libgdal 3.9.*  does not exist (perhaps a typo or a missing channel);\n\u2514\u2500 proj 9.4.0.*  does not exist (perhaps a typo or a missing channel).</pre><pre>linux_ppc64le_numpy1.23python3.11.____cpython: Could not solve for environment specs\nThe following packages are incompatible\n\u251C\u2500 libgdal 3.9.*  does not exist (perhaps a typo or a missing channel);\n\u2514\u2500 proj 9.4.0.*  does not exist (perhaps a typo or a missing channel).</pre><pre>linux_ppc64le_numpy1.26python3.12.____cpython: Could not solve for environment specs\nThe following packages are incompatible\n\u251C\u2500 libgdal 3.9.*  does not exist (perhaps a typo or a missing channel);\n\u2514\u2500 proj 9.4.0.*  does not exist (perhaps a typo or a missing channel).\n                </pre>\n                </div>\n                </details>"
    },
    "richdem": {
      "immediate_children": [],
      "num_descendants": 0,
      "pre_pr_migrator_status": "not solvable (<a href='https://github.com/regro/cf-scripts/actions/runs/9170337419'>bot CI job</a>) @ main\n                <details>\n                <div align=\"left\">\n                <pre>\n                linux_ppc64le_numpy1.22python3.8.____cpython: Could not solve for environment specs\nThe following package could not be installed\n\u2514\u2500 libgdal 3.9.*  does not exist (perhaps a typo or a missing channel).</pre><pre>linux_ppc64le_numpy2.0python3.10.____cpython: Could not solve for environment specs\nThe following package could not be installed\n\u2514\u2500 libgdal 3.9.*  does not exist (perhaps a typo or a missing channel).</pre><pre>linux_ppc64le_numpy2.0python3.11.____cpython: Could not solve for environment specs\nThe following package could not be installed\n\u2514\u2500 libgdal 3.9.*  does not exist (perhaps a typo or a missing channel).</pre><pre>linux_ppc64le_numpy2.0python3.12.____cpython: Could not solve for environment specs\nThe following package could not be installed\n\u2514\u2500 libgdal 3.9.*  does not exist (perhaps a typo or a missing channel).</pre><pre>linux_ppc64le_numpy2.0python3.9.____cpython: Could not solve for environment specs\nThe following package could not be installed\n\u2514\u2500 libgdal 3.9.*  does not exist (perhaps a typo or a missing channel).\n                </pre>\n                </div>\n                </details>"
    },
    "rsgislib": {
      "immediate_children": [],
      "num_descendants": 0,
      "pr_status": "",
      "pr_url": "https://github.com/conda-forge/rsgislib-feedstock",
      "pre_pr_migrator_status": ""
    },
    "taudem": {
      "immediate_children": [],
      "num_descendants": 0,
      "pr_status": "clean",
      "pr_url": "https://github.com/conda-forge/taudem-feedstock/pull/18",
      "pre_pr_migrator_status": ""
    },
    "tuiview": {
      "immediate_children": [],
      "num_descendants": 0,
      "pr_status": "dirty",
      "pr_url": "https://github.com/conda-forge/tuiview-feedstock/pull/61",
      "pre_pr_migrator_status": ""
    },
    "xtensor-zarr": {
      "immediate_children": [],
      "num_descendants": 0,
      "pr_status": "clean",
      "pr_url": "https://github.com/conda-forge/xtensor-zarr-feedstock/pull/14",
      "pre_pr_migrator_status": ""
    }
  },
  "awaiting-parents": [],
  "awaiting-pr": [],
  "bot-error": [
    "r-terra"
  ],
  "done": [
    "tuiview",
    "rsgislib",
    "r-gdalcubes",
    "pyogrio",
    "postgis",
    "pdal",
    "pcraster",
    "ncl",
    "mesher",
    "mdal",
    "mapserver",
    "helios",
    "gdal-csharp",
    "gazebo",
    "exactextract"
  ],
  "in-pr": [
    "heavydb-ext",
    "xtensor-zarr",
    "taudem",
    "rasam",
    "pycoalescence",
    "qgis",
    "pdal_wrench",
    "nansat",
    "lue",
    "isce3",
    "isce2",
    "hexer",
    "dggrid",
    "autorift",
    "acctaudem"
  ],
  "not-solvable": [
    "richdem",
    "rasterio",
    "r-sf",
    "r-rgdal",
    "pygplates",
    "gz-common",
    "gmt",
    "fiona"
  ]
}